### Automated
POST http://localhost:8000/api/automated
Content-Type: application/json

{
  "ps": 500,
  "length_b1_b2": 175,
  "length_b1_b3": 200,
  "ps1": 600,
  "ps2": 300,
  "requested": "de_rand_best_1"
}